### ISSUE TITLE
Looking forward to 2.2

### ISSUE THREAD

**Issue by cinnamoner** [cinnamoner/Feren-OS-2.2-chat#1]

**Comment by cinnamoner** [comment]
@feren Feel at home!

**Comment by feren** [comment]
Hello, PS: It's called 2016.2 Update 2 or '2016.22'

**Comment by cinnamoner** [comment]
@feren There's been much talk about those *transparent panels*. Please explain/illustrate the concept. I guess you know what I'm talking about.

**Comment by feren** [comment]
Basically, when a window is maximised, like in Vista, the panel now goes opaque on some themes including feren Cinnamon and co.

**Comment by cinnamoner** [comment]
@feren That's what I was thinking. Hey, that's great!

**Comment by Elbullazul** [comment]
@feren also, have you thought of pyGTK instead of glide?

**Comment by feren** [comment]
@Elbullazul Not yet, I'll have to check it out

PS: It's safe to say this can be closed @cinnamoner now Update 2 is out
